cabal-version: 3.4
name: oci-distribution-api-hs
version: 0.1.0.0
license: BSD-3-Clause
license-file: LICENSE
author: Mike Ledger
maintainer: haskell@bellroy.com
category: Distribution
build-type: Simple
extra-doc-files: CHANGELOG.md

common common
  ghc-options: -Wall
  default-language: GHC2024

library
  import: common
  -- cabal-gild: discover src/
  exposed-modules:
    OpenContainerImage.Flow.GetLayerByAnnotation
    OpenContainerImage.Manifest
    OpenContainerImage.Manifest.Annotation
    OpenContainerImage.Registry

  build-depends:
    aeson,
    attoparsec,
    base ^>=4.21.2.0,
    bytestring,
    containers,
    http-client,
    http-types,
    modern-uri,
    text,
    unliftio,
    vector,

  hs-source-dirs: src

test-suite oci-distribution-api-hs-test
  import: common
  type: exitcode-stdio-1.0
  build-depends:
    aeson,
    aeson-pretty,
    base ^>=4.21.2.0,
    bytestring,
    oci-distribution-api-hs,
    tasty,
    tasty-golden,

  -- cabal-gild: discover test/
  hs-source-dirs: test
  main-is: spec.hs

executable oci-read-one-layer
  import: common
  build-depends:
    base ^>=4.21.2.0,
    http-client,
    http-client-tls,
    network-uri,
    oci-distribution-api-hs,
    optics,
    optparse-applicative,
    optparse-generic,
    relude,

  main-is: example/oci-read-one-layer.hs
